Add Popup
GoWithMeOrg/go-with-me pull request #61
Opened 2024-03-26 10:13 UTC by AleksandrRazhev

после завершение работы над попапом, нужно удалить изменения в компоненте EventList. Они сделаны только для тестирования работы попапа.

2024-03-26 15:35 UTC, alexbaumgertner commented on src/components/EventList/EventList.tsx
> +import Popup from "../UI-kit/Popup/Popup";
Я думаю, UI-kit — лишний уровень. Все компоненты можно хранить просто в /components

2024-03-26 15:36 UTC, alexbaumgertner commented on src/components/EventList/EventList.tsx
> +    const [showPopup, setShowPopup] = useState<boolean>(true);
Тут возможно TS сам выведет тип из default value
```suggestion
    const [showPopup, setShowPopup] = useState(true);
```

2024-03-26 15:38 UTC, alexbaumgertner requested changes
Убрать лишний слой UI-kit

2024-03-27 14:30 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
@AleksandrRazhev покажи пожалуйста пример, как пользоваться этим компонентом.
Если получится — в StoryBook.

Сейчас я вижу, что нужно много вспомогательных параметров передавать, `containerElement` например. Кажется, Popup может просто рисовать себя в конце DOM-дерева, перед </body>

2024-03-27 14:37 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
Тут может нужен свой CSS-класс, а не все возможные props?

2024-03-27 14:38 UTC, alexbaumgertner requested changes

2024-03-27 14:38 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +        <div className={styles.wrapper} {...wrapperProps}>
Тут может нужен свой CSS-класс, а не все возможные props?

2024-03-27 17:55 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +        <div className={styles.wrapper} {...wrapperProps}>
Пропсы не обязательные. Есть дефолтный className, но, если юзер захочет передать свой класс, то он может это сделать. Если захочет передать другие атрибуты, у него тоже будет такая возможность.

2024-03-27 17:58 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
я несколько раз сталкивался, когда мне нужно попап отрисовать в каком-то конкретном реакт элементе. containerElement не обязательный пропс. Но, в библиотеках, я таким контейнером частто пользовался.

2024-03-27 18:03 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +        <div className={styles.wrapper} {...wrapperProps}>
А не затрет ли это className компонента?

2024-03-27 18:05 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
> в каком-то конкретном реакт элементе. 

Или _у_ конкретного элемента?
Если у элемента будет overflow: hidden — попап обрежется

2024-03-27 20:22 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +        <div className={styles.wrapper} {...wrapperProps}>
Затрет. Я так и ланировал. И в новом className будут только нужные этому элементу стили.

2024-03-27 21:00 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
Испортить можно что угодно. Можно в попап передать display: none,
Контейнер не обязательный элемент. Если юзер не понимает, как его использовать, он его и не будет использовать. Контейнер нужен, например, чтобы показать сообщение у конкретного элемента без высчитывания его координат относительно body.
Если ты принципиально против, я могу убрать. Но, мне кажется этот пропс удобным функционалом.
Пример компонента, который имеет такой же контейнер, которым я много раз пользовался https://rsuitejs.com/components/date-picker/

2024-03-28 12:04 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +        <div className={styles.wrapper} {...wrapperProps}>
А если прописать `onclick="function() { fetch('/hacker/?=documents.cookie') }"` — не пройдет? :)

2024-03-28 12:08 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
> Испортить можно что угодно. Можно в попап передать display: none, Контейнер не обязательный элемент. Если юзер не понимает, как его использовать, он его и не будет использовать. Контейнер нужен, например, чтобы показать сообщение у конкретного элемента без высчитывания его координат относительно body. Если ты принципиально против, я могу убрать. Но, мне кажется этот пропс удобным функционалом. Пример компонента, который имеет такой же контейнер, которым я много раз пользовался https://rsuitejs.com/components/date-picker/

А код его тут? https://github.com/rsuite/rsuite/blob/main/src/Popover/Popover.tsx

2024-03-29 08:59 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
Вот код компонентов, которые я непосредственно использовал
https://github.com/rsuite/rsuite/tree/main/src/DateRangePicker
https://github.com/rsuite/rsuite/tree/main/src/SelectPicker
они принимают пропс container, который HTMLElement или () => HTMLElement

2024-03-29 09:06 UTC, alexbaumgertner commented on src/components/Popup/Popup.tsx
> +        <div className={styles.wrapper} {...wrapperProps}>
> А если прописать `onclick="function() { fetch('/hacker/?=documents.cookie') }"` — не пройдет? :)

Хотя по идее, только мы управляем пропсами, так что тут ок.

2024-03-29 09:08 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
На гитхабе старая версия библиотеки. Я использую rsuite": ^5.31.1

2024-03-29 09:27 UTC, AleksandrRazhev commented on src/components/Popup/Popup.tsx
> +const Popup: FC<PopupProps> = ({ showPopup, setShowPopup, wrapperProps, containerElement, children, ...rest }) => {
в последней редакции компонент Popover так же может принимать container: HTMLElement | (() => HTMLElement) https://rsuitejs.com/components/popover/

2024-03-29 13:57 UTC, merged