add comments
GoWithMeOrg/go-with-me pull request #65
Opened 2024-03-30 07:47 UTC by KseniaRazheva

2024-04-17 17:42 UTC, alexbaumgertner requested changes

2024-04-17 17:42 UTC, alexbaumgertner commented on src/components/Comment/Comment.stories.tsx
> +        userName: "Петя",
Попробуй еще пожалуйста длинное имя, например "Александр Баумгертнер"

2024-04-17 17:42 UTC, alexbaumgertner commented on src/components/Comment/index.ts
> +export * from "./Comment"
Не хватает пустой строки в конце

2024-04-17 17:42 UTC, alexbaumgertner commented on src/components/CommentsList/CommentsList.tsx
> +                        {comments.map(({ commentId, likesNumber, text, userName }) => (
Подскажи, как тут определяется, где комментарий первого уровня, а где ответ?

2024-04-24 20:28 UTC, alexbaumgertner approved these changes

2024-04-24 20:29 UTC, alexbaumgertner commented
![image](https://github.com/GoWithMeOrg/go-with-me/assets/223620/d1f5a30f-4bd0-4f4f-a976-2ba3feefdcbe)

Сборка сломалась вот тут ⬆️

2024-04-25 07:22 UTC, AleksandrRazhev commented
> Fix build

это не мои изменений, это пришло из ветки main после ребейза.

2024-05-14 10:04 UTC, alexbaumgertner approved these changes

2024-05-14 10:07 UTC, merged