Google maps location
GoWithMeOrg/go-with-me pull request #66
Opened 2024-04-03 10:26 UTC by zladen

2024-04-03 20:27 UTC, alexbaumgertner requested changes

2024-04-03 20:27 UTC, alexbaumgertner commented on src/components/GoogleMap/MapHandler.tsx
> +    }, [map, place]);
тут даже возможно так 
```suggestion
    }, [map, place.geometry?.viewport]);
```

@AleksandrRazhev @KseniaRazheva как думаете?

2024-04-03 20:27 UTC, alexbaumgertner commented on src/components/GoogleMap/Geocoding.tsx
> +    const lng = coordinates[0];
вроде можно так

```suggestion
    const [lng, lat] = coordinates;
```

2024-04-03 20:27 UTC, alexbaumgertner commented on src/components/GoogleMap/Geocoding.tsx
> +    const geocodind = useMapsLibrary("geocoding");
```suggestion
    const geocoding = useMapsLibrary("geocoding");
```

2024-04-03 20:27 UTC, alexbaumgertner commented on src/components/GoogleMap/Autocomplete.tsx
> +        });
нужно по unmount сделать отписку и почистить память, `setPlaceAutocomplete(null)`

2024-04-03 20:27 UTC, alexbaumgertner commented on src/components/GoogleMap/Directions.tsx
> +        return () => directionsRenderer.setMap(null);
+ отписка от событий

2024-04-03 20:37 UTC, alexbaumgertner commented
<img width="882" alt="Screenshot 2024-04-03 at 23 36 53" src="https://github.com/GoWithMeOrg/go-with-me/assets/223620/c757d33b-8641-490f-b392-84d1d5c64c56">
http://localhost:3000/events/65c09cabb8a7c9bf11dd4603/edit

ошибка

2024-04-06 06:00 UTC, zladen commented on next.config.js
> +    // reactStrictMode: false,
удалил комментарий

2024-04-06 06:01 UTC, zladen commented on src/app/events/[event_id]/edit/page.tsx
> +import GoogleMap from "@/components/GoogleMap/GoogleMap";
Удалено

2024-04-06 06:01 UTC, zladen commented on src/app/layout.tsx
> +    const API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY as string;
удалено

2024-04-06 06:02 UTC, zladen commented on src/app/layout.tsx
> +                        <APIProviderGoogleMaps>
Тут нужно подумать. Поскольку отдельные компоненты карты мы будем использовать в разных частях приложения. Я еще по экспериментирую с оберткой.

2024-04-06 06:03 UTC, zladen commented on src/components/GoogleMap/MapHandler.tsx
> +    }, [map, place]);
Так не работает зависимость начинает сыпать ошибками.

2024-04-06 06:03 UTC, zladen commented on src/components/GoogleMap/Geocoding.tsx
> +    const lng = coordinates[0];
Так и сделал.

2024-04-06 06:03 UTC, zladen commented on src/components/GoogleMap/Geocoding.tsx
> +    const geocodind = useMapsLibrary("geocoding");
Тут не понял

2024-04-06 06:04 UTC, zladen commented on src/components/GoogleMap/Autocomplete.tsx
> +        });
отписка добавлена

2024-04-06 06:04 UTC, zladen commented on src/components/GoogleMap/Directions.tsx
> +        return () => directionsRenderer.setMap(null);
Тоже добавил.

2024-04-06 10:31 UTC, alexbaumgertner commented on src/components/GoogleMap/Geocoding.tsx
> +    const geocodind = useMapsLibrary("geocoding");
опечатка, смотри последнюю букву

2024-04-06 19:33 UTC, alexbaumgertner approved these changes

2024-04-06 19:35 UTC, alexbaumgertner commented on src/components/GoogleMap/Geocoding.tsx
> +    const geocodind = useMapsLibrary("geocoding");
поправь пожалуйста и можно вливать

2024-04-07 17:39 UTC, merged