feat/add-comments-actions
GoWithMeOrg/go-with-me pull request #84
Opened 2024-08-02 14:36 UTC by AleksandrRazhev

2024-08-09 15:24 UTC, alexbaumgertner commented on src/components/CommentsList/styles.ts
Может тут лучше название для файла "types" или "models"?

2024-08-09 15:26 UTC, alexbaumgertner commented on src/app/api/graphql/route.ts
> +        id: ID
id — это user Id? Что будет, если пользователь поменяет имя userName? Нужно ли будет пройтись по всем комментариям и поменять userName?

2024-08-09 15:27 UTC, alexbaumgertner commented on src/app/api/graphql/route.ts
> +            const filtered = comments.filter(({ replyTo }) => !replyTo).sort(() => -1);
```suggestion
            const firstLevel = comments.filter(({ replyTo }) => !replyTo).sort(() => -1);
```

2024-08-09 15:38 UTC, alexbaumgertner commented on src/components/CommentsList/Comment/Comment.tsx
> +        <div className={styles.comment} id={`comment-id-${_id}`}>
`comment-id-${_id}` можно вынести в константу и потом в ссылке использовать

2024-08-09 15:39 UTC, alexbaumgertner commented on src/components/CommentsList/CommentForm/CommentForm.tsx
> +            const res = await onSaveComment(comment);
```suggestion
            const saveCommentResponse = await onSaveComment(comment);
```

2024-08-09 15:42 UTC, alexbaumgertner commented on src/components/CommentsList/CommentsList.tsx
> +            const res = await saveComment({
```suggestion
            const saveCommentResult = await saveComment({
```
или saveCommentResult, смотря что лучше поджодит

2024-08-09 16:18 UTC, AleksandrRazhev commented on src/app/api/graphql/route.ts
> +        id: ID
id - это id того коммментария, на который реплай сделали.  А  userName - это имя автора комментария, на который реплай.

2024-08-09 16:28 UTC, AleksandrRazhev commented on src/components/CommentsList/CommentsList.tsx
> +            const res = await saveComment({
saveCommentResponse?

2024-08-14 11:53 UTC, alexbaumgertner requested changes

2024-08-14 11:53 UTC, alexbaumgertner commented on src/app/events/[event_id]/page.module.css
> +<<<<<<< HEAD
Осталось нерезолвено

2024-08-14 13:18 UTC, alexbaumgertner approved these changes

2024-08-15 16:47 UTC, alexbaumgertner approved these changes

2024-08-15 16:47 UTC, alexbaumgertner commented on src/components/CommentsList/hooks/useComments.ts
> +import { useSession } from "next-auth/react";
Тут нужно выше на строку поднять

2024-08-21 08:47 UTC, closed without merging